const ELEMENT_ID = {
    CONFIRM_MODAL_OK_BUTTON: "CONFIRM_MODAL_OK_BUTTON",
    NAV_TITLE_CONTAINER: "NAV_TITLE_CONTAINER",
    MENU_SIDEBAR: "MENU_SIDEBAR",
    BREADCRUMB_CONTAINER: "BREADCRUMB_CONTAINER",
    SIDEBAR_TOGGLE_ICON_BUTTON: "SIDEBAR_TOGGLE_ICON_BUTTON",
    VAT_HIDE_BUTTON: "VAT_HIDE_BUTTON",
    ORDER_INFORMATION_CONTAINER: "ORDER_INFORMATION_CONTAINER",
    BUTTON_SIDE_BAR_HIDDEN: "BUTTON_SIDE_BAR_HIDDEN",
    IFRAME_HIDDEN_PRINT: "IFRAME_HIDDEN_PRINT",
    RELOAD_ORDER_PRODUCT_BUTTON_HIDDEN: "RELOAD_ORDER_PRODUCT_BUTTON_HIDDEN",
};

export default ELEMENT_ID;
